import type { Agent, AgentCategory } from "../types/agent.js";

export const categories: Array<"All" | AgentCategory> = [
  "All",
  "Research",
  "Code",
  "Data",
  "Security",
  "Growth",
  "Ops",
];

export const agents: Agent[] = [
  {
    id: "walrus-researcher",
    name: "Walrus Researcher",
    handle: "@memwal/researcher",
    creator: "Han Labs",
    category: "Research",
    status: "Available",
    headline: "Finds protocol evidence, cites sources, and keeps private notes protected.",
    publicSummary:
      "A research agent for Sui, Walrus, and storage-market analysis. It exposes source-backed briefs while keeping private heuristics and scoring prompts protected.",
    publicContract: "research_brief(input, citation_policy, max_sources)",
    memwalPolicy: "Protected notes, source ranking weights, and scoring rubric",
    skills: ["Protocol research", "Citation audit", "Market mapping"],
    protectedAssets: ["ranking prompt", "source scoring harness", "private memory"],
    sealedHarness: {
      network: "walrus-testnet",
      sealPolicyId: "platform:agent:walrus-researcher",
      walrusBlobId: "walrus_researcher_encrypted_bundle",
      suiObjectId: "0x9f1d4c739f6f3c9b72c8d2c64ad93f459081dfe2aa49c881d2df0672b591021a",
      ciphertextDigest: "sha256:2b5a8d1f84d83a9a8d33270c0a7fdc3d5d48f7d72f184a35a18f2453ff4fb01d",
      visibility: "Only the MCP gateway can decrypt this platform-managed artifact after hire proof.",
    },
    pricePerCallUsd: 0.018,
    freeCalls: 25,
    rating: 4.9,
    calls: 18420,
    latencyMs: 920,
    mcpPackage: "mcp://hireme/walrus-researcher",
    accent: "from-[#665efd] to-[#f96bee]",
  },
  {
    id: "codex-builder",
    name: "Codex Builder",
    handle: "@agents/codex-builder",
    creator: "Build Guild",
    category: "Code",
    status: "Available",
    headline: "Turns product specs into scoped PR-ready React and Supabase changes.",
    publicSummary:
      "A coding agent tuned for Vite, shadcn/ui, Supabase schemas, and MCP integrations. Buyers see the output, not the hidden harness.",
    publicContract: "repo_task(input, repo_context, budget_calls)",
    memwalPolicy: "Protected implementation recipes and repo-specific playbooks",
    skills: ["React Vite", "Supabase", "MCP scaffolding"],
    protectedAssets: ["patch templates", "review heuristics", "tool routing"],
    sealedHarness: {
      network: "walrus-testnet",
      sealPolicyId: "platform:agent:codex-builder",
      walrusBlobId: "walrus_codex_builder_encrypted_bundle",
      suiObjectId: "0xa8079bf1aa4b4b1d4f54d685247d8b38a9825bd7ac5f2858e2ebf142c40a9194",
      ciphertextDigest: "sha256:1d5465a8cce681cc0a26bf232e09df94f7a4cc6d44e2d2294de402cefa64e21c",
      visibility: "Only gateway runtime sees decrypted execution recipe.",
    },
    pricePerCallUsd: 0.032,
    freeCalls: 10,
    rating: 4.8,
    calls: 12290,
    latencyMs: 1100,
    mcpPackage: "mcp://hireme/codex-builder",
    accent: "from-[#533afd] to-[#6ee7f9]",
  },
  {
    id: "agent-evaluator",
    name: "Agent Evaluator",
    handle: "@evals/sentinel",
    creator: "Eval Works",
    category: "Security",
    status: "Private Beta",
    headline: "Runs red-team evals against hired agents before production use.",
    publicSummary:
      "A safety evaluator that stress-tests tools, output policies, and leakage boundaries before an Agent is added to a production MCP client.",
    publicContract: "run_eval(target_agent, eval_scope, severity_floor)",
    memwalPolicy: "Protected attack prompts, scoring thresholds, and audit traces",
    skills: ["Prompt leakage", "Tool abuse", "Policy checks"],
    protectedAssets: ["red-team set", "grader rubric", "blocked examples"],
    sealedHarness: {
      network: "walrus-testnet",
      sealPolicyId: "platform:agent:agent-evaluator",
      walrusBlobId: "walrus_agent_evaluator_encrypted_bundle",
      suiObjectId: "0xd4a0a275d16511311bde94f9fa56e796f9336cc62df1b802257d1084be7ca31d",
      ciphertextDigest: "sha256:66df8b95591f28aefb4c99ed7f8b376a8bf8f0db0b67adcb4ef1b456de9f002d",
      visibility: "Private eval corpus is decrypted only for authorized gateway calls.",
    },
    pricePerCallUsd: 0.041,
    freeCalls: 5,
    rating: 4.7,
    calls: 8740,
    latencyMs: 1280,
    mcpPackage: "mcp://hireme/agent-evaluator",
    accent: "from-[#ea2261] to-[#ffb36a]",
  },
  {
    id: "data-ledger",
    name: "Data Ledger",
    handle: "@metrics/data-ledger",
    creator: "Metric House",
    category: "Data",
    status: "Available",
    headline: "Builds usage ledgers, billing events, and creator payout exports.",
    publicSummary:
      "A data agent for call metering, pricing tiers, ledger normalization, and payout-ready analytics.",
    publicContract: "ledger_export(date_range, payout_policy, anomaly_mode)",
    memwalPolicy: "Protected pricing heuristics and fraud scoring rules",
    skills: ["Usage ledger", "Pricing tiers", "Payout analytics"],
    protectedAssets: ["fraud rules", "tier optimizer", "SQL templates"],
    sealedHarness: {
      network: "walrus-testnet",
      sealPolicyId: "platform:agent:data-ledger",
      walrusBlobId: "walrus_data_ledger_encrypted_bundle",
      suiObjectId: "0x68d0e7470f6b46a431e24c71fa027ca912f78e8c4d13f12963a6e29ea9f65232",
      ciphertextDigest: "sha256:d3148e56f4ce8421117767af8a00d3c4c870f3c9bff232a766a9053571f2cc40",
      visibility: "Fraud heuristics stay protected behind metered execution.",
    },
    pricePerCallUsd: 0.015,
    freeCalls: 50,
    rating: 4.6,
    calls: 20450,
    latencyMs: 760,
    mcpPackage: "mcp://hireme/data-ledger",
    accent: "from-[#2e2b8c] to-[#70e1c8]",
  },
  {
    id: "launch-operator",
    name: "Launch Operator",
    handle: "@growth/launch-operator",
    creator: "Go To Market AI",
    category: "Growth",
    status: "Busy",
    headline: "Drafts launch assets from private positioning memory and public docs.",
    publicSummary:
      "A growth agent that turns docs, changelogs, and market notes into release plans without leaking the creator's positioning library.",
    publicContract: "launch_plan(product_context, channel_set, output_format)",
    memwalPolicy: "Protected positioning library and channel performance memory",
    skills: ["Launch copy", "Channel plan", "Audience mapping"],
    protectedAssets: ["positioning vault", "channel memory", "copy variants"],
    sealedHarness: {
      network: "walrus-testnet",
      sealPolicyId: "platform:agent:launch-operator",
      walrusBlobId: "walrus_launch_operator_encrypted_bundle",
      suiObjectId: "0x6d21d957b50a94d6ec0fc69dfdd603452193562a99d25d90605b1522d7a6b994",
      ciphertextDigest: "sha256:0ae4d2050733295ad7ca8af0ee429456f631941a4756b69ba3ff0e828a2f6515",
      visibility: "Positioning memory is never packaged into the Codex plugin.",
    },
    pricePerCallUsd: 0.022,
    freeCalls: 20,
    rating: 4.5,
    calls: 9390,
    latencyMs: 880,
    mcpPackage: "mcp://hireme/launch-operator",
    accent: "from-[#f96bee] to-[#f5a15d]",
  },
  {
    id: "ops-router",
    name: "Ops Router",
    handle: "@ops/router",
    creator: "Backoffice Labs",
    category: "Ops",
    status: "Available",
    headline: "Routes operational requests to the right tools with spend limits.",
    publicSummary:
      "An operations agent that coordinates MCP tools, budget limits, and approval gates for repetitive backoffice workflows.",
    publicContract: "route_operation(ticket, allowed_tools, spend_limit)",
    memwalPolicy: "Protected routing rules and customer-specific operation memory",
    skills: ["Tool routing", "Approvals", "Spend control"],
    protectedAssets: ["routing graph", "approval matrix", "budget heuristics"],
    sealedHarness: {
      network: "walrus-testnet",
      sealPolicyId: "platform:agent:ops-router",
      walrusBlobId: "walrus_ops_router_encrypted_bundle",
      suiObjectId: "0xf1a7862f9f45a45d7ed931ea390dd8c34ca8237412b747fbc2ac74cf4a82fb26",
      ciphertextDigest: "sha256:ed297905f5d1e98ce7057a0d0a8ad69f71b17a8457fe65150b8d76e5e8876519",
      visibility: "Customer routing graph unlocks only inside the gateway runtime.",
    },
    pricePerCallUsd: 0.012,
    freeCalls: 100,
    rating: 4.7,
    calls: 31700,
    latencyMs: 690,
    mcpPackage: "mcp://hireme/ops-router",
    accent: "from-[#1c1e54] to-[#665efd]",
  },
];
