import type { Agent, AgentCategory, AgentTeam } from "../types/agent.js";

export const categories: Array<"All" | AgentCategory> = [
  "All",
  "Research",
  "Code",
  "Data",
  "Security",
  "Growth",
  "Ops",
];

const tryCallAllowance = 100;

const protocolIntelligenceTeam: AgentTeam = {
  id: "protocol-intelligence",
  name: "Protocol Intelligence Team",
  handle: "@teams/protocol-intelligence",
  owner: "Han Labs",
  headline: "Research, evidence, and usage-ledger agents for Sui and Walrus teams.",
  publicSummary:
    "A coordinated catalog for protocol research and metered data exports. Buyers pay per routed MCP call to the selected Agent.",
  agentCount: 3,
  accent: "from-[#665efd] to-[#70e1c8]",
  billing: {
    unit: "team_bundle",
    basePriceUsd: 0.049,
    includedCalls: 40,
    overagePricePerCallUsd: 0.014,
    note: "Agent calls are charged by the executing Agent ledger.",
  },
};

const buildOpsTeam: AgentTeam = {
  id: "build-ops",
  name: "Build Ops Team",
  handle: "@teams/build-ops",
  owner: "Build Guild",
  headline: "Implementation, routing, and operations agents for product teams.",
  publicSummary:
    "A builder-facing catalog that combines repo implementation, operational routing, and spend control behind Agent-level hires.",
  agentCount: 3,
  accent: "from-[#533afd] to-[#6ee7f9]",
  billing: {
    unit: "team_bundle",
    basePriceUsd: 0.058,
    includedCalls: 25,
    overagePricePerCallUsd: 0.018,
    note: "Each Agent is hired and metered independently. Codex calls one Agent at a time.",
  },
};

const launchSafetyTeam: AgentTeam = {
  id: "launch-safety",
  name: "Launch Safety Team",
  handle: "@teams/launch-safety",
  owner: "Go To Market AI",
  headline: "Launch planning with safety checks before public release.",
  publicSummary:
    "Growth output and eval checks are packaged as Agent-level MCP capabilities so buyers can plan, test, and ship from one marketplace.",
  agentCount: 3,
  accent: "from-[#ea2261] to-[#f5a15d]",
  billing: {
    unit: "team_bundle",
    basePriceUsd: 0.063,
    includedCalls: 20,
    overagePricePerCallUsd: 0.021,
    note: "Launch drafts and preflight evals are priced per executing Agent call.",
  },
};

export const agents: Agent[] = [
  {
    id: "walrus-researcher",
    name: "Walrus Researcher",
    handle: "@memwal/researcher",
    creator: "Han Labs",
    team: protocolIntelligenceTeam,
    teamRole: "Lead researcher",
    listedIndividually: true,
    category: "Research",
    status: "Available",
    headline: "Finds protocol evidence, cites sources, and keeps private notes protected.",
    publicSummary:
      "A research agent for Sui, Walrus, and storage-market analysis. It exposes source-backed briefs while keeping private heuristics and scoring prompts protected.",
    publicContract: "research_brief(input, citation_policy, max_sources)",
    memwalPolicy: "Protected notes, source ranking weights, and scoring rubric",
    skills: ["Protocol research", "Citation audit", "Market mapping"],
    protectedAssets: ["ranking prompt", "source scoring harness", "private memory"],
    sealedHarness: {
      network: "walrus-testnet",
      sealPolicyId: "platform:agent:walrus-researcher",
      walrusBlobId: "walrus_researcher_encrypted_bundle",
      suiObjectId: "0x9f1d4c739f6f3c9b72c8d2c64ad93f459081dfe2aa49c881d2df0672b591021a",
      ciphertextDigest: "sha256:2b5a8d1f84d83a9a8d33270c0a7fdc3d5d48f7d72f184a35a18f2453ff4fb01d",
      visibility: "Only the MCP gateway can decrypt this platform-managed artifact after hire proof.",
    },
    pricePerCallUsd: 18,
    freeCalls: tryCallAllowance,
    rating: 4.9,
    calls: 18420,
    latencyMs: 920,
    avgInputTokens: 1240,
    avgOutputTokens: 860,
    resultPreview: {
      title: "Source-backed protocol brief",
      summary:
        "Returns a ranked source list, confidence notes, and storage-market implications.",
      sample:
        "Walrus storage evidence brief with 6 citations, risk tags, and recommended follow-up reads.",
    },
    mcpPackage: "mcp://hireme/walrus-researcher",
    accent: "from-[#665efd] to-[#f96bee]",
  },
  {
    id: "source-scout",
    name: "Source Scout",
    handle: "@memwal/source-scout",
    creator: "Han Labs",
    team: protocolIntelligenceTeam,
    teamRole: "Evidence gatherer",
    listedIndividually: false,
    category: "Research",
    status: "Available",
    headline: "Collects relevant protocol sources and prepares citation candidates.",
    publicSummary:
      "A research support agent that gathers sources before a protocol brief is written.",
    publicContract: "source_scan(topic, source_policy, max_candidates)",
    memwalPolicy: "Protected source ranking weights and citation heuristics",
    skills: ["Source discovery", "Citation prep", "Protocol docs"],
    protectedAssets: ["source scoring harness", "private source memory"],
    sealedHarness: {
      network: "walrus-testnet",
      sealPolicyId: "platform:agent:source-scout",
      walrusBlobId: "walrus_source_scout_encrypted_bundle",
      suiObjectId: "0x22e0e0d16e4a2bb8b77708f018861372f41f5beec4a1f21d9af8edc44b1c0a77",
      ciphertextDigest: "sha256:f8f86dca4b6a10c62ff4d978933f05b7fb7e48a4043475396ea63d7500e67a19",
      visibility: "Only gateway runtime sees the private source scoring flow.",
    },
    pricePerCallUsd: 11,
    freeCalls: tryCallAllowance,
    rating: 4.5,
    calls: 11240,
    latencyMs: 640,
    avgInputTokens: 820,
    avgOutputTokens: 520,
    resultPreview: {
      title: "Protocol source scan",
      summary:
        "Returns candidate sources, relevance notes, and citation confidence signals.",
      sample:
        "Source scan with docs, forum threads, release notes, and evidence priority.",
    },
    mcpPackage: "mcp://hireme/source-scout",
    accent: "from-[#665efd] to-[#70e1c8]",
  },
  {
    id: "codex-builder",
    name: "Codex Builder",
    handle: "@agents/codex-builder",
    creator: "Build Guild",
    team: buildOpsTeam,
    teamRole: "Implementation specialist",
    listedIndividually: false,
    category: "Code",
    status: "Available",
    headline: "Turns product specs into scoped PR-ready React and Supabase changes.",
    publicSummary:
      "A coding agent tuned for Vite, shadcn/ui, Supabase schemas, and MCP integrations. Buyers see the output, not the hidden harness.",
    publicContract: "repo_task(input, repo_context, budget_calls)",
    memwalPolicy: "Protected implementation recipes and repo-specific playbooks",
    skills: ["React Vite", "Supabase", "MCP scaffolding"],
    protectedAssets: ["patch templates", "review heuristics", "tool routing"],
    sealedHarness: {
      network: "walrus-testnet",
      sealPolicyId: "platform:agent:codex-builder",
      walrusBlobId: "walrus_codex_builder_encrypted_bundle",
      suiObjectId: "0xa8079bf1aa4b4b1d4f54d685247d8b38a9825bd7ac5f2858e2ebf142c40a9194",
      ciphertextDigest: "sha256:1d5465a8cce681cc0a26bf232e09df94f7a4cc6d44e2d2294de402cefa64e21c",
      visibility: "Only gateway runtime sees decrypted execution recipe.",
    },
    pricePerCallUsd: 32,
    freeCalls: tryCallAllowance,
    rating: 4.8,
    calls: 12290,
    latencyMs: 1100,
    avgInputTokens: 1880,
    avgOutputTokens: 1320,
    resultPreview: {
      title: "PR-ready implementation plan",
      summary:
        "Returns scoped repo edits, affected files, test plan, and rollout notes.",
      sample:
        "Supabase billing ledger patch plan with schema changes, RLS checks, and verification commands.",
    },
    mcpPackage: "mcp://hireme/codex-builder",
    accent: "from-[#533afd] to-[#6ee7f9]",
  },
  {
    id: "schema-migrator",
    name: "Schema Migrator",
    handle: "@agents/schema-migrator",
    creator: "Build Guild",
    team: buildOpsTeam,
    teamRole: "Database specialist",
    listedIndividually: true,
    category: "Data",
    status: "Available",
    headline: "Plans Supabase schema changes, RLS updates, and migration verification steps.",
    publicSummary:
      "A database-focused agent that can be hired directly for migration work.",
    publicContract: "schema_change_plan(goal, current_schema, safety_level)",
    memwalPolicy: "Protected migration recipes and RLS review heuristics",
    skills: ["Supabase", "RLS", "Migrations"],
    protectedAssets: ["migration playbooks", "RLS checklist", "rollback templates"],
    sealedHarness: {
      network: "walrus-testnet",
      sealPolicyId: "platform:agent:schema-migrator",
      walrusBlobId: "walrus_schema_migrator_encrypted_bundle",
      suiObjectId: "0x4a08d0c9c80c4a8238fd31414c2808c7ff0ca9c6fefedee4e8851b0b8cd6d91b",
      ciphertextDigest: "sha256:7ca98441fefbe0501f5b81557ed72b4414d48f2ac59c9fbcd7c3a8f4660f1e90",
      visibility: "Only gateway runtime sees protected migration and rollback heuristics.",
    },
    pricePerCallUsd: 24,
    freeCalls: tryCallAllowance,
    rating: 4.6,
    calls: 9820,
    latencyMs: 980,
    avgInputTokens: 1510,
    avgOutputTokens: 1120,
    resultPreview: {
      title: "Migration safety plan",
      summary:
        "Returns schema diff guidance, RLS checks, rollback notes, and verification commands.",
      sample:
        "Supabase migration plan with policy checks, seed updates, and smoke tests.",
    },
    mcpPackage: "mcp://hireme/schema-migrator",
    accent: "from-[#533afd] to-[#70e1c8]",
  },
  {
    id: "agent-evaluator",
    name: "Agent Evaluator",
    handle: "@evals/sentinel",
    creator: "Go To Market AI",
    team: launchSafetyTeam,
    teamRole: "Preflight evaluator",
    listedIndividually: false,
    category: "Security",
    status: "Private Beta",
    headline: "Runs red-team evals against hired agents before production use.",
    publicSummary:
      "A safety evaluator that stress-tests tools, output policies, and leakage boundaries before an Agent is added to a production MCP client.",
    publicContract: "run_eval(target_agent, eval_scope, severity_floor)",
    memwalPolicy: "Protected attack prompts, scoring thresholds, and audit traces",
    skills: ["Prompt leakage", "Tool abuse", "Policy checks"],
    protectedAssets: ["red-team set", "grader rubric", "blocked examples"],
    sealedHarness: {
      network: "walrus-testnet",
      sealPolicyId: "platform:agent:agent-evaluator",
      walrusBlobId: "walrus_agent_evaluator_encrypted_bundle",
      suiObjectId: "0xd4a0a275d16511311bde94f9fa56e796f9336cc62df1b802257d1084be7ca31d",
      ciphertextDigest: "sha256:66df8b95591f28aefb4c99ed7f8b376a8bf8f0db0b67adcb4ef1b456de9f002d",
      visibility: "Private eval corpus is decrypted only for authorized gateway calls.",
    },
    pricePerCallUsd: 41,
    freeCalls: tryCallAllowance,
    rating: 4.7,
    calls: 8740,
    latencyMs: 1280,
    avgInputTokens: 1560,
    avgOutputTokens: 940,
    resultPreview: {
      title: "Leakage and tool-abuse eval",
      summary:
        "Returns red-team findings, severity labels, reproduction notes, and mitigations.",
      sample:
        "Prompt leakage audit with 4 high-signal attacks, blocked examples, and policy fixes.",
    },
    mcpPackage: "mcp://hireme/agent-evaluator",
    accent: "from-[#ea2261] to-[#ffb36a]",
  },
  {
    id: "data-ledger",
    name: "Data Ledger",
    handle: "@metrics/data-ledger",
    creator: "Han Labs",
    team: protocolIntelligenceTeam,
    teamRole: "Ledger analyst",
    listedIndividually: false,
    category: "Data",
    status: "Available",
    headline: "Builds usage ledgers, billing events, and creator payout exports.",
    publicSummary:
      "A data agent for call metering, pricing tiers, ledger normalization, and payout-ready analytics.",
    publicContract: "ledger_export(date_range, payout_policy, anomaly_mode)",
    memwalPolicy: "Protected pricing heuristics and fraud scoring rules",
    skills: ["Usage ledger", "Pricing tiers", "Payout analytics"],
    protectedAssets: ["fraud rules", "tier optimizer", "SQL templates"],
    sealedHarness: {
      network: "walrus-testnet",
      sealPolicyId: "platform:agent:data-ledger",
      walrusBlobId: "walrus_data_ledger_encrypted_bundle",
      suiObjectId: "0x68d0e7470f6b46a431e24c71fa027ca912f78e8c4d13f12963a6e29ea9f65232",
      ciphertextDigest: "sha256:d3148e56f4ce8421117767af8a00d3c4c870f3c9bff232a766a9053571f2cc40",
      visibility: "Fraud heuristics stay protected behind metered execution.",
    },
    pricePerCallUsd: 15,
    freeCalls: tryCallAllowance,
    rating: 4.6,
    calls: 20450,
    latencyMs: 760,
    avgInputTokens: 980,
    avgOutputTokens: 620,
    resultPreview: {
      title: "Usage ledger export",
      summary:
        "Returns normalized billing events, anomaly flags, and creator payout rows.",
      sample:
        "CSV-ready MCP call ledger with refund markers, token totals, and payout subtotals.",
    },
    mcpPackage: "mcp://hireme/data-ledger",
    accent: "from-[#2e2b8c] to-[#70e1c8]",
  },
  {
    id: "launch-operator",
    name: "Launch Operator",
    handle: "@growth/launch-operator",
    creator: "Go To Market AI",
    team: launchSafetyTeam,
    teamRole: "Launch operator",
    listedIndividually: true,
    category: "Growth",
    status: "Busy",
    headline: "Drafts launch assets from private positioning memory and public docs.",
    publicSummary:
      "A growth agent that turns docs, changelogs, and market notes into release plans without leaking the creator's positioning library.",
    publicContract: "launch_plan(product_context, channel_set, output_format)",
    memwalPolicy: "Protected positioning library and channel performance memory",
    skills: ["Launch copy", "Channel plan", "Audience mapping"],
    protectedAssets: ["positioning vault", "channel memory", "copy variants"],
    sealedHarness: {
      network: "walrus-testnet",
      sealPolicyId: "platform:agent:launch-operator",
      walrusBlobId: "walrus_launch_operator_encrypted_bundle",
      suiObjectId: "0x6d21d957b50a94d6ec0fc69dfdd603452193562a99d25d90605b1522d7a6b994",
      ciphertextDigest: "sha256:0ae4d2050733295ad7ca8af0ee429456f631941a4756b69ba3ff0e828a2f6515",
      visibility: "Positioning memory is never packaged into the Codex plugin.",
    },
    pricePerCallUsd: 22,
    freeCalls: tryCallAllowance,
    rating: 4.5,
    calls: 9390,
    latencyMs: 880,
    avgInputTokens: 1420,
    avgOutputTokens: 980,
    resultPreview: {
      title: "Launch asset pack",
      summary:
        "Returns channel-specific launch copy, audience map, and conversion checkpoints.",
      sample:
        "Release plan with homepage copy, email sequence, X thread, and KPI guardrails.",
    },
    mcpPackage: "mcp://hireme/launch-operator",
    accent: "from-[#f96bee] to-[#f5a15d]",
  },
  {
    id: "conversion-copywriter",
    name: "Conversion Copywriter",
    handle: "@growth/conversion-copywriter",
    creator: "Go To Market AI",
    team: launchSafetyTeam,
    teamRole: "Conversion copy specialist",
    listedIndividually: false,
    category: "Growth",
    status: "Available",
    headline: "Drafts offer-aware copy variants for landing pages, emails, and launch ads.",
    publicSummary:
      "A copy specialist that drafts from protected positioning memory.",
    publicContract: "copy_variants(offer, audience, channel, tone)",
    memwalPolicy: "Protected positioning library and copy performance memory",
    skills: ["Landing copy", "Email copy", "Offer framing"],
    protectedAssets: ["copy variants", "positioning memory", "channel heuristics"],
    sealedHarness: {
      network: "walrus-testnet",
      sealPolicyId: "platform:agent:conversion-copywriter",
      walrusBlobId: "walrus_conversion_copywriter_encrypted_bundle",
      suiObjectId: "0x9d4b8cb3dfbbdfc2a2a96d85843c12c3bf76cb25b48b38bc930a29df2ab3ec6e",
      ciphertextDigest: "sha256:541dffb8ce02d2fe8d6c325e6269ece4df582ba65e0f5f0643b6ebe34e275ad4",
      visibility: "Only gateway runtime sees protected positioning and copy examples.",
    },
    pricePerCallUsd: 18,
    freeCalls: tryCallAllowance,
    rating: 4.4,
    calls: 7310,
    latencyMs: 820,
    avgInputTokens: 1100,
    avgOutputTokens: 760,
    resultPreview: {
      title: "Conversion copy variants",
      summary:
        "Returns landing page sections, CTA variants, and channel-specific launch copy.",
      sample:
        "Offer copy pack with hero, feature, trust, email, and ad variants.",
    },
    mcpPackage: "mcp://hireme/conversion-copywriter",
    accent: "from-[#f96bee] to-[#f5a15d]",
  },
  {
    id: "ops-router",
    name: "Ops Router",
    handle: "@ops/router",
    creator: "Build Guild",
    team: buildOpsTeam,
    teamRole: "Workflow router",
    listedIndividually: false,
    category: "Ops",
    status: "Available",
    headline: "Routes operational requests to the right tools with spend limits.",
    publicSummary:
      "An operations agent that coordinates MCP tools, budget limits, and approval gates for repetitive backoffice workflows.",
    publicContract: "route_operation(ticket, allowed_tools, spend_limit)",
    memwalPolicy: "Protected routing rules and customer-specific operation memory",
    skills: ["Tool routing", "Approvals", "Spend control"],
    protectedAssets: ["routing graph", "approval matrix", "budget heuristics"],
    sealedHarness: {
      network: "walrus-testnet",
      sealPolicyId: "platform:agent:ops-router",
      walrusBlobId: "walrus_ops_router_encrypted_bundle",
      suiObjectId: "0xf1a7862f9f45a45d7ed931ea390dd8c34ca8237412b747fbc2ac74cf4a82fb26",
      ciphertextDigest: "sha256:ed297905f5d1e98ce7057a0d0a8ad69f71b17a8457fe65150b8d76e5e8876519",
      visibility: "Customer routing graph unlocks only inside the gateway runtime.",
    },
    pricePerCallUsd: 12,
    freeCalls: tryCallAllowance,
    rating: 4.7,
    calls: 31700,
    latencyMs: 690,
    avgInputTokens: 740,
    avgOutputTokens: 430,
    resultPreview: {
      title: "Routed operation plan",
      summary:
        "Returns selected tools, approval gates, spend limit checks, and next action.",
      sample:
        "Support ticket routing decision with owner, allowed MCP tools, and escalation threshold.",
    },
    mcpPackage: "mcp://hireme/ops-router",
    accent: "from-[#1c1e54] to-[#665efd]",
  },
];
